### ISSUE TITLE
Deploy command not working with python 3.5.2

### ISSUE THREAD

**Issue by jkenny** [gilt/nova#12]
When trying to run nova deploy with python 3.5.2 I get the error below. Downgrading to python 2.7.11 fixed the problem.

```
Compressing deployment bundle...
|--------------------------------------------------| 0% Traceback (most recent call last):
  File "/Users/jkenny/.pyenv/versions/3.5.2/bin/nova", line 9, in <module>
    load_entry_point('gilt-nova==10.8.10', 'console_scripts', 'nova')()
  File "/Users/jkenny/.pyenv/versions/3.5.2/lib/python3.5/site-packages/nova/cli/main.py", line 83, in main
    app.run()
  File "/Users/jkenny/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/Users/jkenny/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/Users/jkenny/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/Users/jkenny/.pyenv/versions/3.5.2/lib/python3.5/site-packages/nova/cli/controllers/deploy/deploy.py", line 62, in default
    deployer.deploy()
  File "/Users/jkenny/.pyenv/versions/3.5.2/lib/python3.5/site-packages/nova/core/deploy/deploy_stack.py", line 62, in deploy
    revision_etag = self.__build_upload_revision(deployment_bucket_name, key)
  File "/Users/jkenny/.pyenv/versions/3.5.2/lib/python3.5/site-packages/nova/core/deploy/deploy_stack.py", line 93, in __build_upload_revision
    revision_etag = self._aws_manager.push_revision(deployment_bucket_name, key, self._code_deploy_app, self._nova_deploy_dir)
  File "/Users/jkenny/.pyenv/versions/3.5.2/lib/python3.5/site-packages/nova/core/managers/aws_manager.py", line 205, in push_revision
    gz_out.add(os.path.join(nova_deploy_dir, f), arcname=f, progress=tarfile.progressprint)
  File "/Users/jkenny/.pyenv/versions/3.5.2/lib/python3.5/site-packages/nova/core/utils/tarfile_progress.py", line 41, in add
    return tarfile.TarFile.add(self, name, arcname, recursive, exclude, filter)
TypeError: add() takes from 2 to 5 positional arguments but 6 were given
Cleaning up deployment bundle...
```

**Comment by barryoneill** [comment]
I got hit by this as well, I worked around it with the following changes: https://github.com/gilt/nova/pull/28
